USE EMPRESA_AC_2


SELECT *FROM EMPLEADOS AS a INNER JOIN ESTCIVIL AS b ON a.ID_ESTCIVIL = b.ID_ESTCIVIL

SELECT *FROM EMPLEADOS AS a LEFT JOIN ESTCIVIL AS b ON a.ID_ESTCIVIL = b.ID_ESTCIVIL

SELECT *FROM EMPLEADOS AS a RIGHT JOIN ESTCIVIL AS b ON a.ID_ESTCIVIL = b.ID_ESTCIVIL


